version: "3.7"

networks:
  proxy:
    external: true
  task_manager:

services:
  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: api
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - task_manager
      - proxy

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - task_manager

volumes:
  mariadb_data:
  redis:
